### ISSUE TITLE
Scroll Bar indicator disappears at bottom of albums

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#31]
I finally remember the other issue. If you scroll to the bottom of an album the scroll indicator will disappear at the bottom. Like there is a bar across the bottom that it falls behind.

**Comment by Nostang3** [comment]
The scroll bar is no longer hidden behind the bottom bar. 
However, it looks like the scroll bar is hidden behind the top bar.

**Comment by puregallery** [comment]
That is expected...the list now spans the whole screen and actually goes under the top bar too...
The scroll bar simply follows the list around its whole length.

**Comment by Nostang3** [comment]
I only bring it up because on other gallery apps the scroll bar indicator is between the top and bottom bars and doesn't span the whole height of the screen. It's what I expect so it's why I listed it as a bug/issue.

**Comment by Nostang3** [comment]
I noticed that when on the main Albums view that the scroll bar acts funky. I have 5 albums in 2 column view. The 5th album barely hangs below the visible viewing area. If I scroll down just the small amount needed to make the 5th album fully visible the scroll bar will jump down to roughly  20-30% down the side of the phone and stop. Considering that I'm at the bottom of the view, I think the scroll bar should be at the bottom and not somewhere in the middle. 

When viewing photos in an album, I noticed that the scroll bar will stop moving before I get to the bottom of the collection of photos. It is also not fully seated at the bottom of the viewing area, and has some space still to go.  This is much easier to notice in my album with 1200 photos than compared to my album with 100.

**Comment by puregallery** [comment]
While viewing an album, I added padding at the bottom. So, the scroll range will account for that padding as well and change the sidebar's position appropriately. I guess this will be an impediment for albums with a lot of images - I will remove this.
I didn't change anything for album list view yet. Let me look into that.

**Comment by Nostang3** [comment]
So this might be nitpicking but I want to give you the option because your name is on the app, lol. When scrolling down from the very top, the scroll bar doesn't move until you are about a page down. I feel like it should be moving as soon as you start scrolling. 

When at the bottom, it immediately stops when you can't scroll anymore. This works as expected.

**Comment by puregallery** [comment]
lol...I fixed the bottom part and now the top is broken...let me take a look. The math in that scroller is crazy man...

**Comment by Nostang3** [comment]
Scroll bar still hangs at the top and you have to scroll down a little bit before it actually starts moving.

**Comment by puregallery** [comment]
In the album that you are observing this in, how many items do you have? and how many columns?

**Comment by Nostang3** [comment]
Cursor now stops at expected point at bottom of large album.
