### ISSUE TITLE
Debugging the new home page

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#98]
I'm not sure what triggers it, but occasional my camera folder(which happens to be the first folder alphabetically) will be pinned to the top. If I go into folder options it will show pin to top checked. If I uncheck it, it doesn't lose it's position. I have to swipe PG from recents menu to get things to reset.

**Comment by puregallery** [comment]
Camera album is pinned to top by default. It is the default behavior for some gallery apps, which I adopted.
Also, I have the new home page version ready....can you help me test it? I can send you a debug build, which you can have along with the play store version.

**Comment by Nostang3** [comment]
It just doesn't seem consistent. I get that it should be at the top of a non pinned album view for easy access. But it is sometimes at the top before the pins and other times after the pinned. My current experience with PG is the the Pinned albums take priority over the camera folder. 

Yeah, sure. I'm down for testing.

**Comment by puregallery** [comment]
The intention was to have the camera album have precedence over any other pinned album...I guess the sorting is a bit broken for that case. I will look into that.

here is a link to the build...
https://drive.google.com/open?id=1HhkcpQv9wN1RhU1cH_dEIAgNyu9V4bBf

Few options in the toolbar are still missing though...

**Comment by puregallery** [comment]
Hey...I identified a few issues and am working on fixing them...
Just test out the new design and let me know how you feel.
Btw...you can now copy/move items from hybrid albums(timeline, tags, locations etc)

**Comment by Nostang3** [comment]
I like it. The Albums screen might take a little to get used to but I like it's quick access to the files. One thing I did notice is that it doesn't remember your view selection when you close out of PG. So if I'm on album and exit and come back it defaults to Timeline. 

I also just noticed the eager loading option in the settings. Makes swiping through photos so much more pleasant as they are already rendered. 

Another issue is that if you click the title of the album in Album view it won't open the album You have to click a little below it or to the empty area to the side to be able to open it. Took me a few to get it to work as I kept clicking on the title.

**Comment by puregallery** [comment]
>The Albums screen might take a little to get used to but I like it's quick access to the files

This has been there since the beginning...it is the nested view in the albums screen....you can select it from the three dot menu

>I did notice is that it doesn't remember your view selection when you close out of PG

Yup...that is not implemented yet

>I also just noticed the eager loading option in the settings

This has been in the app for at least 2 releases. If you often have large images, this might take up a lot of memory and slow down the app. I tested this on an album with pictures about 300MB each...and my phone held up good though.

>You have to click a little below it or to the empty area to the side to be able to open it

Jeez...I thought it was my fingers when I ran into this. Will look into it.

**Comment by Nostang3** [comment]
My bad for not noticing the options or forgetting. I can get into a rut with using apps. I'll make it a point to mess with more settings on the debug version

**Comment by puregallery** [comment]
It's fine...no worries.
I enabled analytics to see what viewType users would prefer...and very few people use the nested type either way. What are your thoughts on it? I can increase the height of each row(album)...which would make the media items more legible. Right now, each album has about 1/3 of the screen height.

Should I leave the nested option as the default? You will be able to change it from the toolbar in the final release though.

**Comment by Nostang3** [comment]
> Btw...you can now copy/move items from hybrid albums(timeline, tags, locations etc)

How does this work? I tried long pressing on a picture in timeline and it gave me the option to tag, info, view, or set album cover. For tags or library(I didn't see location) i can't long press the items. I can't long press in Albums view either. 

On my pixel xl in the albums view I only get 3 if I had only 1 row showing in each album. In most albums I have 2 rows showing so I only see 2 full albums. But as far as image size goes, I can pretty clearly see what is in each picture without needing open it. Do you plan on adding an option to be able to move/copy pictures on this nested view? 

I think leaving as the default is fine since you can change it if you want something different. People might use it more often if they see it and forgot about the view like me. 

Also, scrolling through the tagged view stutters alot. I have a lot of tags and a lot of items tagged with those tags. So in some cases one tag could have hundreds of photos attached to it. I also probably have 200 tags.

**Comment by puregallery** [comment]
>How does this work? I tried long pressing on a picture in timeline and it gave me the option to tag, info, view, or set album cover. For tags or library(I didn't see location) i can't long press the items. I can't long press in Albums view either.

Oops, I enabled that option for debug builds only...I have been testing that on my debug builds for quite a while to identify potential failures. Eitherway, since I sent you a release version of the dev builds, it didn't appear. I will send another build shortly...

>On my pixel xl in the albums view I only get 3 if I had only 1 row showing in each album. In most albums I have 2 rows showing so I only see 2 full albums. But as far as image size goes, I can pretty clearly see what is in each picture without needing open it. Do you plan on adding an option to be able to move/copy pictures on this nested view?

Yes, I tinkered with this a bit. When you have more than 6(need to check the number) items in the albums, I display 2 rows...else, the album will be displayed in a single row. Move/copy is going to be quite hard in the nested view frankly. I will look into it...but cannot promise a timeline for it.

>Also, scrolling through the tagged view stutters alot. I have a lot of tags and a lot of items tagged with those tags. So in some cases one tag could have hundreds of photos attached to it. I also probably have 200 tags.

I know that it stutters the first time those images are loaded and cached. Let me know if this continues...Also, I want to reproduce your steps to see how bad it is. You use a pixel 2 right?

**Comment by Nostang3** [comment]
OG Pixel XL.

**Comment by puregallery** [comment]
Ok...I will try it out.
I uploaded a new build to the same folder...please try that.

**Comment by Nostang3** [comment]
Installed. Should I be looking for any particular changes between the previous build?

A quick test of the tagged view still has some stutter. I took the time to scroll slowly to the bottom of the list to it would create thumbnails for all the items but scrolling fast seems to lag on loading those thumbnails back. That or I've hit some limit of cached thumbnails and it is recreating them again as I scroll.

**Comment by puregallery** [comment]
>Installed. Should I be looking for any particular changes between the previous build?

I enabled the move/copy from all places in this build...also, a few fixes to the toolbar options.

I didn't look into the stuttering issue yet...I have an old Nexus 6P running Oreo, which had a bit of stuttering when I tested. I'll see what I can do. 
Btw...the stuttering doesn't appear when I scroll through the album horizontally...I see it only while scrolling vertically.

**Comment by Nostang3** [comment]
I only see the stuttering in vertical scrolling in nested Tags View. In an Albums or on Timeline it's fine.

**Comment by puregallery** [comment]
If you are using aspect ratio, can you disable the it from settings and see if it gets better?

**Comment by Nostang3** [comment]
That removes the stuttering.

Also, have you thought about making the whole splash screen the same green as the icon. I think that would mimic the popular apps Twitch, Snapchat and such all use the App color as the whole background.

**Comment by puregallery** [comment]
Hmm...that's a good idea frankly. Let me try it out.
Found a small optimization to remove the stuttering issue. Can you download the build from drive and give a try? Try this with aspect ratio as well.

**Comment by Nostang3** [comment]
Did you make the change in this build or for a future release?

The stuttering is gone in nested view.

**Comment by puregallery** [comment]
>Did you make the change in this build or for a future release?

Still testing this one.
>The stuttering is gone in nested view.

I was excited about this...glad this was addressed

**Comment by puregallery** [comment]
Pushed a new build to the drive folder...
I have changed the splash screen now...and fixed the click issues on the nested album names.
I believe this is close to a final version. I will test this a bit further and release it over the weekend.

**Comment by Nostang3** [comment]
The splash screen looks very nice now! Click issue is working. 

An issue I noticed was that if you change from like Timeline to Albums/Library while it's refreshing it makes the screen while. Attempting to scroll brings the pictures back though but the blankness keeps coming back.

**Comment by Nostang3** [comment]
Since we doing debug issues here for now, if you move a photo(s) from one album, emptying it, to another, and back out to the main album view the folder still shows the files till you swipe down to refresh.

**Comment by puregallery** [comment]
I fixed the move issue...
I couldn't reproduce the blank issue, but attempted a small fix at it...let me know if it helped.

Remembering the tab position is still WIP

**Comment by Nostang3** [comment]
I think the fix worked for the blank issue and the move issue is fixed and very responsive now.

**Comment by puregallery** [comment]
I saw the blank issue just now...looks like this is not fixed completely

**Comment by Nostang3** [comment]
On the albums tagged with a couple pinned albums, the first pinned album(second in list) and the second to last album are switched when you open the image from nested view. The albums are in the "right" order but when you open a nested image in the second album it opens an image from the second to the bottom album and vice versa.

**Comment by puregallery** [comment]
Fixed the wrong image opening issue...try the latest build.
I think the blank issue should not happen anymore.

I saw an issue where the TimeLine ended up empty though...if you see this, and know a good path to reproducing it...please let me know.

**Comment by Nostang3** [comment]
It now opens the correct image on nested view. I'll keep an eye for the timeline issue. 

Edit: It seems that untoggling show hidden doesn't remove items from the timeline that are hidden.

**Comment by puregallery** [comment]
I pushed a new build to the drive folder...
Fixed the empty timeline issue...and an issue with the black theme.
The hidden items in the timeline view looks a little weird. The items will animate as soon as you scroll it.

EDIT: Ah, found the reason for the blank screens and for the hidden items. Will push a fix for this soon.

**Comment by Nostang3** [comment]
So I went into a hidden album in nested Album view, selected two photos and deleted them, but they were not removed from the folder. At least the thumbnails wasn't. I did it again, thinking I might have not hit the okay button and hit just off to the side and cleared the dialog. Same thing. I had to pull down to refresh before the files disappeared. 

Should we create a thread for Debug issues so we aren't adding to this one?

**Comment by puregallery** [comment]
The bug that started this story is addressed eitherway...I changed the title.

I will look into the delete issue.

**Comment by puregallery** [comment]
I pushed a new build...
Can you check the delete issue there?
And I believe this is the last of the 'UI not loading properly' issue.

**Comment by Nostang3** [comment]
Delete issue is still present. If after you delete a photo and the photos is still selected, swiping down to refresh will put into a seemingly infinite load animation. Hitting back arrow will remove the selection. Hitting it again will exit to the main album view. Backing out of the album does not refresh the view to remove the album/photo from the album.

**Comment by puregallery** [comment]
Ah, sorry...I had to rewrite all the moving/copy logic since the app has to handle the hybrid albums now.
I forgot to add the post-delete code here. The files are deleted, but the UI was not attempting to refresh after that.

**Comment by puregallery** [comment]
Ok...check the new build now. Delete issue is fixed.

Let me know if you come across any other issues. This is close to a final build.

**Comment by Nostang3** [comment]
The issue is not fixed unfortunately. It is still not refreshing the folder when a photo is deleted.

**Comment by puregallery** [comment]
Yikes...called a deprecated method. Please try now. 
Also, I have changes to remember the home page position....you can access them in settings.

**Comment by Nostang3** [comment]
I don't know if I'm not grabbing the right version or my phone isn't updating to the new app but i'm getting the blank screen issue, the album isn't refreshing after deletion, and it's not remembering it's place like you say it should.

**Comment by puregallery** [comment]
Hmm....that's odd. I just did a clean build and uploaded it again.
Maybe your drive app is still giving you a cached version. Try refreshing and make sure the upload time is the same as this message's timestamp.

**Comment by Nostang3** [comment]
I'm opening it in a private window in firefox on desktop then copying the file to the device and installing from there. I'll try uninstalling the file and installing the new version.

**Comment by Nostang3** [comment]
I think it's the right version now. I deleted a file and it properly removed the picture but the refresh animation is stuck on screen while in the album. Backing out will clear the animation.

It isn't remembering the home screen view. Backing out of the app then opening it back up always starts on the start screen. I"m using nested view. 

Blank screen hasn't reappeared yet.

**Comment by puregallery** [comment]
You need to make a selection from the settings for this to work...the default screen it reverts to is Timeline
Or is this not working despite that?

>I think it's the right version now. I deleted a file and it properly removed the picture but the refresh animation is stuck on screen while in the album. Backing out will clear the animation.

I see the animation not being dismissed too...let me look into that.

**Comment by Nostang3** [comment]
No, that's my bad, missed that part about setting it in settings. That works now that I'm doing it correctly.

**Comment by puregallery** [comment]
Cool...good to know.
I just pushed a build fixing the delete issue.

**Comment by Nostang3** [comment]
The delete issue seems to be fixed, but I noticed that moving suffers from the same issue.

**Comment by puregallery** [comment]
Did you see this in a regular album, or a hybrid one - like tags, timeline..

**Comment by Nostang3** [comment]
I can't say for certain. Because you can't see what album the file is in to be sure. It does something when I move on timeline(photo sort changes and moves around) and when I go to album view after it shows the right folder. It seems that it only happens when I'm on Album view and inside a folder.

**Comment by puregallery** [comment]
Moving items in timeline(hybrid albums) is a bit complicated...I cannot simply not show the albums that the selected items belong to...and the items that belong to the same destination folder are simply ignored.

I was actually planning on showing a summary at the end of move/copy process to explain which items are moved successfully...and which ones are ignored. I did test the move process today, and didn't see any irregularities. I will test this a bit further to make sure it is not messy.

Once this issue is resolved, I am planning to push the release

**Comment by puregallery** [comment]
Did you get a chance to test this further?

**Comment by Nostang3** [comment]
I think timeline works as expected when moving copying. I can move a file from one folder to another(emptying the album) then switch to Album and it shows the updated albums. But I if I move from inside an album on Albums view to another album(emptying the album) then it doesn't refresh the album after the move. You either have to swipe down or back out of the album.

**Comment by Nostang3** [comment]
I'll put this here but when moving copying while folders are hidden, if you choose the option to show hidden, it doesn't show the hidden files. And if you close that dialog then try to show hidden and try to copy move the show hidden toggle doesn't show hidden. You have to tell it to show hidden twice before they show. It's like the check box loses it's status or isn't updated. 

Edit: This was on Album view, going into the album, and then choosing to move copy. Then when it didn't work backing out to the root album view and then using the three dot menu to toggle show hidden.

**Comment by puregallery** [comment]
Good catch...can confirm this.
Btw...am in the process of changing phones...so, cannot have all my media set up for a few days.
Please report any issues that you see.

**Comment by Nostang3** [comment]
There was an issue deleting a photo while in an album and it losing track of what photo to open. I haven't been able to recreate it but wanted to mention it somewhere. It was like the index of an array was off by 1 or something.

**Comment by puregallery** [comment]
Can you check out the new build...
I fixed the 'show hidden' issue while on the "move/copy to" dialog, 'screensaver share' issue and the 'new tag' issue.
I also had to make a few changes to the way splash screen is rendered to get it working on devices of all densities. Can you check if it is looking good on your device?

**Comment by Nostang3** [comment]
Quick note, I noticed that the logo the splash is off center on my Pixel XL. It's more towards the left side of the screen. 

Edit: I noticed that when moving the show hidden does work, but now shows all folders including empty ones, and when you select a folder to move too, the dialog does not go away. 

Edit2: Screen saver settings aren't saving in the settings menu and I don't get a prompt for saving anymore. I need to add that it no longer prompts for any album.

**Comment by puregallery** [comment]
Pushed an update with fixes to the issues you specified...
Also, the 'save as default' didn't make much sense in the screensaver options...so removed that. Let me know if there are good reasons to bring it back

**Comment by Nostang3** [comment]
Move dialog now disappears but the albums isn't refreshed after to show the changes. I have to swipe down to refresh for the album to update. 

The slideshow dialog is now back and when sharing from a shuffled slideshow it now send the right photo. As far as the save as default, I don't think I'll miss it. I feel like most people would set it and forget it. And the options are so simple that changing them is easy and the feature isn't used enough to warrant more efficiency. 

And for the logo, I am not sure if it's actually off now that I've opened it a bunch of times. I think the predominate left hand part of logo makes your eyes focus on it which shifts the balance from the center to the left giving the illusions of off center. Measuring from the start of each side of the logo shows an equidistant from the edge.

**Comment by puregallery** [comment]
>Move dialog now disappears but the albums isn't refreshed after to show the changes. I have to swipe down to refresh for the album to update.

As opposed to before, I am not updating the hidden preferences after requesting to show hidden folders from the 'move dialog'. To see hidden albums, you need to request that change from home page. Does this make sense?

The logo is not really rounded, nor does it maintain perfect symmetry...I guess this is fine. The only reason I picked it is because it sort of looks like an horizontal 'P'

**Comment by Nostang3** [comment]
Yup, makes total sense. I like it that way. But just in case so we are on the same page, I was talking about inside the album. If I move a photo out of the album via the dialog, it does not reflect that change when inside that album. I have to swipe down to refresh so it removes the photo from said album.

**Comment by puregallery** [comment]
>If I move a photo out of the album via the dialog, it does not reflect that change when inside that album. I have to swipe down to refresh so it removes the photo from said album.

Oh, I will look into that.

**Comment by puregallery** [comment]
btw...about this...
>I noticed that when moving the show hidden does work, but now shows all folders including empty ones

Is showing empty folders helpful? Or should I show just the non-empty ones?

**Comment by Nostang3** [comment]
> Is showing empty folders helpful? Or should I show just the non-empty ones?

I think this came up before, I think you mentioned making it an option in settings for it. It would benefit me to only show the hidden folders that are currently populated. Because otherwise it could potentially have way to many folders to scroll through. The root directory for my photos is constantly adding or removing folders. A lot of them are empty for most of the time.

**Comment by puregallery** [comment]
Fixed the empty folders issue, and 'view not refreshing after move' issue.
Please check the latest build.

**Comment by Nostang3** [comment]
> Fixed the empty folders issue

So the show hidden things partially works. It does show some of the hidden folders currently populated but also showing some empty folders.  I think it's more empty folders showing than populated ones. 

> 'view not refreshing after move

'The move issue is resolved. When I move a photo out of an album emptying it the folder does update and how it being empty.

**Comment by Nostang3** [comment]
> There was an issue deleting a photo while in an album and it losing track of what photo to open. I haven't been able to recreate it but wanted to mention it somewhere. It was like the index of an array was off by 1 or something.

Figured out the delete issue or at least one of them. If you filter your view for a couple tags with the 'And' option, and then delete one of the photos from the filtered view, the remaining photos index will be off. When you open a photo in media viewer it will show the photo about 13 pics back in the filtered view. 

It's also doing that thing again when you exit out of media viewer it scrolls the page back up to where you can't see the photo you just viewed  in the list anymore.

Is the scroll bar removed or is it just not appearing on some albums? I remember seeing it on some but not all the time. So in the album I'm currently in, I don't have a scroll bar to quick slide down or jump to a point in the album. I have to manually swipe to get it to scroll.

Edit: it came back after exiting the album and going back into it.

**Comment by puregallery** [comment]
> So the show hidden things partially works. It does show some of the hidden folders currently populated but also showing some empty folders. I think it's more empty folders showing than populated ones.

So, this is bit of a new implementation. You need to 'Clear data' for the app since this tracks empty folders a bit different going ahead.

**Comment by Nostang3** [comment]
That worked. The correct folders are showing but the dialog is sticking again and not disappearing.

**Comment by puregallery** [comment]
>That worked. The correct folders are showing but the dialog is sticking again and not disappearing.

Ah, got this...fixing it.

>Figured out the delete issue or at least one of them. If you filter your view for a couple tags with the 'And' option, and then delete one of the photos from the filtered view, the remaining photos index will be off.

I will look into it.

**Comment by puregallery** [comment]
Can you check the newest build now? I changed how the filtering works in the app...The delete issue should also be fixed now.

**Comment by Nostang3** [comment]
So I am trying to filter by a tag, and I've selected two pics but when I try to open them in media viewer, This overlay(dims screen a bit) and no photo is shown. Trying to compare two photos.

**Comment by puregallery** [comment]
Ok...fixed that and pushed a new build...Let me know if you see any other issues.
Also, I have added search for the Album and Tags view. Do try it out.
Searching within the albums is a WIP...and I plan to release the app without it for now.

**Comment by Nostang3** [comment]
So the media viewer issue is fixed.

I did notice that when I deleted a photo at the top that it showed that the whole album was empty. I backed out and the album was still there and populated. And at one time I swiped down to refresh on the album and they disappeared as well. 

I tried the search but nothing happened. The view didn't change and it didn't show any results on either album or tag view.

**Comment by puregallery** [comment]
>I did notice that when I deleted a photo at the top that it showed that the whole album was empty. I backed out and the album was still there and populated. And at one time I swiped down to refresh on the album and they disappeared as well.

I don't follow the issue here...Did you mean the home page didn't refresh automatically? Or did the album view itself showed wrong images?

>I tried the search but nothing happened. The view didn't change and it didn't show any results on either album or tag view.

Something's not happy in the release build...this is working on debug builds. I will look into it.

**Comment by puregallery** [comment]
Wait....search is enabled only on the 'Grid' style of the albums/tags. I need to add it to the nested views.

**Comment by Nostang3** [comment]
> I don't follow the issue here...Did you mean the home page didn't refresh automatically? Or did the album view itself showed wrong images?

I was in an album comparing two pictures. So if you select two photos and then hit the media viewer button the photos won't appear. If you only open one photo while in an album then it will open it just fine.

**Comment by puregallery** [comment]
>So the media viewer issue is fixed.

Oh, my bad...you reported that issue is fixed...I don't see it in the app too. Maybe doing this after a delete is still messy...I'll look into it.

You were saying something about the delete issue here...I don't see that happening.
>I did notice that when I deleted a photo at the top that it showed that the whole album was empty. I backed out and the album was still there and populated. And at one time I swiped down to refresh on the album and they disappeared as well.

**Comment by Nostang3** [comment]
Yeah, the latest build fixes the issue where I couldn't open two photos in media viewer. 

>You were saying something about the delete issue here...I don't see that happening.

It's only happened that one time. I haven't been able to recreate it. It might take a specific case to get it do it.

**Comment by puregallery** [comment]
Sounds good.
I am going to push the update today...
This is looking quite stable.

**Comment by Nostang3** [comment]
So I got the "No media to display here!" here message again. I added a new picture to the album. added tag to the photo, then filtered by that tag, selected the two photos that were similar to compare via media viewer, added tags to both photos, then changed exif data on new photo. When i backed out the album had already arranged that photo for the new exif data(since I sort by creation date) but I swiped down to refresh anyway, and the photos disappeared and that message was present. Backing out again clears the issue. 

I ran into the move photo and emptying album delete issue in the latest build. It keeps the photo there.

**Comment by puregallery** [comment]
About the "No media to display here" issue, were you using the regular album or the tag album?

Refresh inside an album is getting quite buggy...sigh....time to rewrite that part I guess.

**Comment by Nostang3** [comment]
I was in the album view.

**Comment by puregallery** [comment]
Ok...I attempted a fix without having to rewrite the whole piece, and it's looking good to me.
Can you test the build now and see if it works well...

I was not able to reproduce the delete issue at all...that might be pending. But let me know if they show up again.

**Comment by puregallery** [comment]
btw...can you drop me an email at puregallery247@gmail.com

**Comment by Nostang3** [comment]
The delete issue is still present for the latest build. Now when I swipe to refresh it doesn't remove the photo from the album, it doesn't disappear. When I back out it the album is removed though because I emptied it when I remove the photo. So the issue seems to stem around being the last photo in the album. If I delete a photo when there is two, it deletes and removes fine inside the album. But when I try to delete the last photo in the album it doesn't remove the photo.

**Comment by puregallery** [comment]
>But when I try to delete the last photo in the album it doesn't remove the photo.

This is the culprit...awesome...thanks for this.

**Comment by puregallery** [comment]
Aright....give the latest build from drive a spin...the issues should be gone

**Comment by Nostang3** [comment]
The delete issue seems to be fixed. Deleting the last photo in an album properly removes the file and give the empty directory message.

**Comment by puregallery** [comment]
Ah, thank god...I will push the release today. Thanks for your help.

**Comment by Nostang3** [comment]
I think I found an edge case where moving a photo that empties an album won't clear like the delete.  I tested it a couple times to confirm.

**Comment by puregallery** [comment]
Ok...I can push a hotfix tonight. Btw, did you see the What's new dialog after updating?

**Comment by Nostang3** [comment]
I don't remember seeing it to be honest but that doesn't mean I didn't. I'll remember to look when I install the hotfix later.

**Comment by puregallery** [comment]
The What's new dialog was missing...
Either way, sorry for the delay on the hotfix...got my new phone(S10+) yesterday...spent the whole day backing up stuff and restoring them.

Will push it today.

**Comment by Nostang3** [comment]
Congrats. MKBHD says it's the phone to beat for 2019. All it's really missing is the Pixel 3 camera. And i Know how it is for restoring for a new/replacement phone. Thanks Zeus for TB+ and root.

**Comment by puregallery** [comment]
Thanks...The phone is really amazing...they have a new wide-lens for both the cameras, which is really good.

The hardware for Pixel camera is not the best part really...it is the software that produces good results. There are  a few mods of their camera apk which work well on other devices too...I was testing all those mods yesterday and the results are quite good...especially the night scene mode. Check this out if you are interested...
https://www.celsoazevedo.com/files/android/google-camera/

The boot loader for US variants of Samsung are not yet unlockable...so, I had to live without root for the past few years. I use my old Nexus 6P for a few Xposed modules. Anyway, this is the reason my setup was quite slow...I had to 'restore' most things manually.

**Comment by Nostang3** [comment]
True, the software does most the heavy lifting but even with the gcam port it doesn't do as well as it does as the pixel + camera at least according to MKBHD. 

I've been holding off on upgrading simply because Xposed isn't stable on O yet, and non existent on Pie. There is the branched version of it but I'm not sure if I want to venture into that yet until it's gotten some usage by others and vetted. I might have to deal with the beta version because my modules are working on it and then be able to get a Pixel 2 and just downgrade to Oreo.

**Comment by puregallery** [comment]
>True, the software does most the heavy lifting but even with the gcam port it doesn't do as well as it does as the pixel + camera at least according to MKBHD.

Didn't know about that video...need to watch that.
The Gcam port will not get the device working as good as the Pixels for sure...but it increased the clarity for pictures in a few scenarios. I will definitely use that for night scene mode for a long time.

I haven't used Xposed or viper or AdAway in a long time...I miss them frankly. I wanted to switch to pixel last year...but Google does not give much preference to the hardware of their devices...this plus I have access to a lot of Pixel's at my work that I didn't feel like I missed them.

**Comment by puregallery** [comment]
Pushed an update to play store...

**Comment by Nostang3** [comment]
Saw the update dialog this time. The dialog did say nested viewing was disabled yet I am using it. 

It seems pretty smooth. There was the instance where I was comparing photos and one of them thumbnails went black. I could still open the file but when in the album it was black/missing. I did edit the exif so maybe the refresh after was messing with it?

Does eager loading take a bit to start up on a fresh run? I noticed that comparing two photos it didn't load the photos in advance but after a bit they were pre-loading.

**Comment by puregallery** [comment]
>Saw the update dialog this time. The dialog did say nested viewing was disabled yet I am using it.

Nested folders was a different folder structure view I had in the left drawer...I will bring that back in the next update.

>I could still open the file but when in the album it was black/missing

I will look into this. In the meantime, you can 'Clear Cache' to lose the black thumbnail.

>Does eager loading take a bit to start up on a fresh run? I noticed that comparing two photos it didn't load the photos in advance but after a bit they were pre-loading.

On a fresh run, since the app will be loading/caching all images...there is a chance of this happening.

**Comment by Nostang3** [comment]
> Nested folders was a different folder structure view I had in the left drawer...I will bring that back in the next update.

I wasn't sure, just thought I'd mention/ask.

> I will look into this. In the meantime, you can 'Clear Cache' to lose the black thumbnail.

This issue fixed itself when I exited the album. So no extreme method is needed to fix it.

**Comment by puregallery** [comment]
yikes....found a bug while changing the sort type on albums...it always maintains the DateDescending while opening full images...but the thumbnails are following the selected sort order.

**Comment by Nostang3** [comment]
Nice find. 

I believe I found that it looks like clearing the tag filter removes the scroll bar.

**Comment by puregallery** [comment]
>I believe I found that it looks like clearing the tag filter removes the scroll bar.

Found the issue causing this too...

**Comment by Nostang3** [comment]
If you have a photo and you enter tag mode, if you select a bunch of tags, then create a new one, then after it's created hit apply, all in one dialog, it only applies the new tag.

**Comment by puregallery** [comment]
I'm guessing not all the tags are checked after you created the new tag too...
I will look into it.

**Comment by Nostang3** [comment]
> I'm guessing not all the tags are checked after you created the new tag too...

Correct, I thought this was an issue before IIRC.

**Comment by Nostang3** [comment]
Updated. Still get the occasional empty directory after deletion. Steps that seem to produce it consistently. 

Add new file to album. Go into album, tag photo with a couple tags, filter for the applied tags with AND operator, then select newly tagged photo and another similar photo, open media viewer, find out which file to delete, then delete photo. 

This might just be happening in tag filtered view but I believe it  might happen in the normal unfiltered view.

**Comment by puregallery** [comment]
>Still get the occasional empty directory after deletion

lol...this thing keeps haunting me. I did test the scenario you mentioned and didn't see it before.
Anyway, something else caught my eye and probably both these issues are related. Once you filter an album and open the filter dialog again, it only shows the filtered tags, and not the full list of tags available in that album.

Also, I received feedback from the play store about a bug regarding backgrounding the app...after backgrounding, when the OS kills the app because of low memory, it fails to open gracefully. This apparently happens all the time on devices with low RAM. When Android clears the memory of an app, they should remove it from the recent apps list as well....I don't understand the need to keep a blank reference to killed apps.
Anyway, took me quite a while to reproduce this consistently to add a fix.
I will look into the delete issue now.

**Comment by puregallery** [comment]
Can you test the latest build from the drive folder to test this? 
I fixed the tags issue and tested out your bug as well...I didn't see it happening.

**Comment by Nostang3** [comment]
I tried the tag issue and it wasn't fixed. I entered tag mode on a photo, selected two tags, then tried to add one, after adding a new tag, only the new tag was checked.

**Comment by puregallery** [comment]
Oh...I meant the 'empty message' after deleting content...
>Add new file to album. Go into album, tag photo with a couple tags, filter for the applied tags with AND operator, then select newly tagged photo and another similar photo, open media viewer, find out which file to delete, then delete photo.

The 'add new tag' is not fixed yet.

**Comment by Nostang3** [comment]
So, the directory is emptying itself like before after tagging a new phone, comparing photos, and deleting that new photo. Be the first photo in the album being deleted. 

Also, while scrolling the title bar at the top is appearing and disappearing.

**Comment by puregallery** [comment]
Let me know if this is the right sequence...
After you compare the two photos using the option on the bottom bar, You click back...then unselect the photo you don't want to delete, and click delete on the toolbar.

**Comment by Nostang3** [comment]
Just to be clear:

1. Add new photo to album
2. Select photo, then enter tag mode and tag it with a couple tags.
3. Filter view inside the album to filter for the tags added using the AND operator so only photos with both tags appear.
4. Select the photo I just tagged then scroll looking for it's similar.
5. Find similar and select it. 
6. Open media viewer to compare size, resolution, and crop.
7. Back out, unselect the wanted photo.
8. Delete using the delete option at top.
9. See the album refresh itself after the deletion and then all photos disappear and it says no media to display or something.

**Comment by puregallery** [comment]
I just followed these steps and couldn't reproduce...something's weird. Can you try the build again?
Also, in the old build, this bug exists...check if it happens first to identify if this is a build issue.
>Once you filter an album and open the filter dialog again, it only shows the filtered tags, and not the full list of tags available in that album.

PS: Am creating the build again to be safe..

**Comment by puregallery** [comment]
>Also, while scrolling the title bar at the top is appearing and disappearing.

Umm...this is a feature...and I had it for a while in there

**Comment by Nostang3** [comment]
Yes, but I don't think you envisioned it to look like a rave party. Lol. It doesn't do it just when I stop, it does it all the time while scrolling, flashing at me.

**Comment by puregallery** [comment]
Lol...is this happening only in the album view? or the home page as well? 

btw...Did you check the empty message issue on the latest build?

**Comment by Nostang3** [comment]
> Lol...is this happening only in the album view? or the home page as well?

I believe it is only happening in the album view and it's not all the time. I think it is like the scroll bar disappearing, there is something that triggers it to start doing that. I don' notice it doing it now, so I'll try to remember what I did right before the next time I notice it. 

> btw...Did you check the empty message issue on the latest build?

Sorry got busy. I tested it just now following my previous steps and it didn't give me the No Media message till I cleared the Filtered Tag view then refreshed the album by swiping down to refresh and then it gave me the message.

**Comment by puregallery** [comment]
>it didn't give me the No Media message till I cleared the Filtered Tag view then refreshed the album by swiping down to refresh

Cool...so the issue is related to tags bug I found. Thanks for this.

**Comment by puregallery** [comment]
>Sorry got busy. I tested it just now following my previous steps and it didn't give me the No Media message till I cleared the Filtered Tag view then refreshed the album by swiping down to refresh and then it gave me the message.

Ok...this should be fixed. Can you test the build and let know.

Working on this issue now
>If you have a photo and you enter tag mode, if you select a bunch of tags, then create a new one, then after it's created hit apply, all in one dialog, it only applies the new tag.

PS: That was simpler than expected. Fixed both issues in the latest build in the drive folder

**Comment by Nostang3** [comment]
> Ok...this should be fixed. Can you test the build and let know.

I tried this and I was able to delete the file and it I did not get the no media message. I did get two different refresh animations. The small spinning circle in the background and the big dialog in the foreground. I feel like it should be one or the other.

I was not able to view a photo after I tagged the new photo(following the established steps), then filtered by tags. I click on the picture and didn't open. I cleared the filter and I could open a photo. The next time I followed the steps(minus adding a new photo again), without leaving the album, when I opened the photo in question it opened a different photo. One previous in the filtered list. 

>PS: That was simpler than expected. Fixed both issues in the latest build in the drive folder

The new tag issue is working as expected.

**Comment by puregallery** [comment]
>I did get two different refresh animations. The small spinning circle in the background and the big dialog in the foreground. I feel like it should be one or the other.

Instead of duplicating code in a method, I simply reused it. Unfortunately, that method shows the swipeRefresh. Anyway, this bugs me too and I will revisit after the major issues are fixed. 
My other projects are creeping up on me fast...and I want to fix all the blocking issues before I take a break for those.

I will look into the other issue today.

**Comment by puregallery** [comment]
>I was not able to view a photo after I tagged the new photo(following the established steps), then filtered by tags. I click on the picture and didn't open. I cleared the filter and I could open a photo. The next time I followed the steps(minus adding a new photo again), without leaving the album, when I opened the photo in question it opened a different photo. One previous in the filtered list.

Can you try this with the build in drive..

**Comment by Nostang3** [comment]
> Can you try this with the build in drive..

I tested this with a couple photos and I was able to view the photos without issue. I didn't run into an issue where it didn't open the photo or opened the wrong one.

**Comment by puregallery** [comment]
Awesome...I will release these fixes today.

**Comment by puregallery** [comment]
I gave the search inside 'album view' a try...can you test it out and let me know how you feel about it. You can access it from Timeline as well.

Right now, it only tries to search for image titles. I plan to extend search to tags and locations.

**Comment by Nostang3** [comment]
It seems to work well and fast. It is case sensitive though so it finds files with "IMG" but not with "img", not sure if that was intentional.

**Comment by puregallery** [comment]
Twas not intended...it was supposed to ignore case. Will fix that.

>Yes, but I don't think you envisioned it to look like a rave party. Lol. It doesn't do it just when I stop, it does it all the time while scrolling, flashing at me.

Did you see this happen again? I attempted a fix at that...not sure if it got fixed since I didn't come across this in my testing.

**Comment by Nostang3** [comment]
I can safely say I haven't had an epileptic seizure in the currently update.

**Comment by Nostang3** [comment]
Do you have plans to speed up the app? I cant use the app for the first 5 seconds that is opened. If I try then when it finishes refreshing, it stops when I'm scrolling and pulls me back up to the top.  have to sit there and wait for it to finish scanning. Similar with the deleting of files in folder or whole albums. If I have to delete multiple albums, I have to scroll down, delete, scroll down, delete, etc for each time an album is deleted. Selecting multiple albums in Grid view would mitigate the need to scroll all the time. Or adding back in the reshuffle without resetting scroll position.

**Comment by puregallery** [comment]
>If I try then when it finishes refreshing, it stops when I'm scrolling and pulls me back up to the top. have to sit there and wait for it to finish scanning.

This is the case for just nested views...This should not happen for the grid view or in timeline. I can have an option in settings to disable the auto-scan for the first launch. This way, you need to enable the scan only if you think it is not accurate. Addressing this completely will take a bit more time...Nested layout is not an easy thing to mess with unfortunately.
>If I have to delete multiple albums, I have to scroll down, delete, scroll down, delete, etc for each time an album is deleted.

I was not aware that this is happening in a grid view...lemme verify that.
>Do you have plans to speed up the app? 

My other projects have a release coming up soon...I will be tied up with that for at least a week. 

PS: I attempted a quick fix to this, not yet final...but can you check the build from drive and report how it feels?

**Comment by Nostang3** [comment]
> I was not aware that this is happening in a grid view...lemme verify that.

I tested in Grid just now to verify that it was in both but you're right it doesn't happen in Grid. I should have checked. 

> I can have an option in settings to disable the auto-scan for the first launch.

I can go back to using Grid till Nested is more streamlined. 

In grid though it won't show hidden until the refresh is complete. It sits and wait for the refresh to complete on startup.

**Comment by puregallery** [comment]
>In grid though it won't show hidden until the refresh is complete. It sits and wait for the refresh to complete on startup.

Ah, I have the 'clear hidden after exit' enable all the time...no wonder I didn't see this. This can be fixed.

Did you test the nested folders on the develop folder? I have a solution for that...and it looked good in my initial testing.

**Comment by Nostang3** [comment]
No, because I accidentally just deleted it. Lol. Could you upload it again?

**Comment by puregallery** [comment]
lol...no worries, reuploaded it now.
The fix turned out to be quite easy actually. But I don't delete albums as frequently as you. Maybe you can give me a better idea about this fix.

The hidden albums at startup is not fixed in this...

**Comment by puregallery** [comment]
>In grid though it won't show hidden until the refresh is complete. It sits and wait for the refresh to complete on startup.

Can you explain the steps here? I don't see this on my device. I can toggle hidden even while the scan is running, and it updates the items just fine.

**Comment by Nostang3** [comment]
> Did you test the nested folders on the develop folder? 

The fix is nice. It resorts the albums without resetting the scroll position in Nested View. 

> Can you explain the steps here? I don't see this on my device. I can toggle hidden even while the scan is running, and it updates the items just fine.

1. Open PG.
2. Immediately try to toggle show hidden

Previously it would not show the hidden albums until refresh was complete. I think it is still the same now but the refresh seems to work quicker in the new debug build so by the time I toggle show hidden the refresh is completing.

**Comment by puregallery** [comment]
Awesome...I usually wait for at least a week before pushing new updates. I will push the release with these fixes some time next week.
Btw, found a bug related to search in the timeline view. I will push that too along with this.

**Comment by puregallery** [comment]
Sorry about the delay man...ran into a few more bugs and it took a bit more time to wrap them up.
I will push the update today.

**Comment by puregallery** [comment]
Found a bug which prevents column change...need to push another update tomorrow I guess.

**Comment by puregallery** [comment]
wow, silence for this long...so you didn't find any new bugs? That's a positive sign :D

**Comment by Nostang3** [comment]
Things have been quiet and I haven't been using it as heavy. But now that you mention I did notice that if you filter for a tag, then edit exif data for a photo so that it changes position in the album view it will throw off things. You'll open a photo and get a different one. I think that is the only issue that comes to mind. A quick back out of the album fixes it. 

There was there one time where I resumed the session after not using it for awhile I think it force closed on me, but did not give a send report dialog. I haen't been able to reproduce it.

**Comment by puregallery** [comment]
Cool....nothing major so far then.
I will look into the 'opening wrong image' issue...that's an easy fix.

**Comment by Nostang3** [comment]
Found another. If you have two photos selected, and in media viewer, then delete one of them, when it backs out to refresh the album and delete the file via the new menu deletion option, after the file is deleted the selection of the two photos moves to another set of two photos. I imagine it keeps the same index numbers of the photos after the deletion & refresh. 

So pick two photos
Go to media viewer to compare them
Three dot menu then delete
Watch as it backs out of the media viewer and moves the photo selection.

**Comment by puregallery** [comment]
Cool...i'll work on these over the weekend.

**Comment by puregallery** [comment]
Sorry for the delay...did you see anything else?

I will be pushing out an update for these today...along with the swipe refresh being active after a delete.

**Comment by Nostang3** [comment]
No worries. I haven't noticed anything else.

**Comment by Nostang3** [comment]
Hey, I'm seeing an issue where Eager Loading isn't always active even though the option is checked. I think closing the app or toggling it off and on, will get it to work again.

**Comment by puregallery** [comment]
I did change it a bit for screensaver...I will look into it.
Does this happen all the time? Or did it just happen once?

**Comment by Nostang3** [comment]
It seems to happen pretty often. I don't use the screensaver. It just seems like it stops working at some point. I notice it everytime I add a new photo to an album and compare it with a similar photo.

**Comment by puregallery** [comment]
I made a few changes to the eager loading logic while changing a bit of screensaver...I will look into it.

**Comment by Nostang3** [comment]
Hey say this weird bug where it loaded the nested view of the albums in really small sizes and the app was running slow. When you tried to tag things, the check mark would not fully animate. You had to start scrolling before it would finish the animation. Not sure how it happened. 

I don't know if it's related but there are also times, where some of the images on the nested album view will deload for awhile.

**Comment by puregallery** [comment]
Umm...What does deload mean? Did you have a greyish placeholder instead of the image thumbnail?

**Comment by Nostang3** [comment]
No greyish placeholder. It's black or clear(I use the black theme). It's seems like the image retains its space because some images were there and some weren't.

**Comment by puregallery** [comment]
Is the eager loading still an issue?
Also, did you see the 'deload' issue again?

**Comment by Nostang3** [comment]
I haven't noticed on Pie that eager loading has stopped. At most I might notice a small moment of loading the full res picture but only when I first open an album. Seems to go away after I swipe a few photos. 

I also haven't seen the issue of "deload". Pie is handling file management a lot better. I'm not having to rescan folders often. I occasionally have to when new folders are created or it hasn't detected changes yet.
